### ISSUE TITLE
docker-compose.yml has wrong version number

### ISSUE THREAD

**Issue by devnoff** [EOSIO/patroneos#17]
OS: ubuntu 16.04
Docker version 18.03.1-ce, build 9ee9f40
docker-compose version 1.8.0

I found `patroneos/docker-compose.yml` has wrong version number.

It occurs following error:

> ~/patroneos$ docker-compose up
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by ericiles** [comment]
Version 3.0 was introduced into docker-compose with docker-compose [1.10.0](https://github.com/docker/compose/releases/tag/1.10.0). You will need to update your docker-compose to use this docker-compose file.
