### ISSUE TITLE
Will not compile due to error in filter.go

### ISSUE THREAD

**Issue by HuweyII** [EOSIO/patroneos#25]
$ go build -o patroneosd *.go
\# command-line-arguments
./filter.go:122: undefined: json.Valid

**Comment by jeffreyssmith2nd** [comment]
Can you share what OS and what version of Go you're using?

**Comment by HuweyII** [comment]
Sure.  Ubuntu 16.04.4 LTS

go version go1.6.2 linux/amd64

**Comment by jeffreyssmith2nd** [comment]
We are only actively testing/supporting Go 1.10 right now. If you upgrade your version, it should build successfully.
