### ISSUE TITLE
JSON Array handling for `push_transactions` action

### ISSUE THREAD

**Issue by redjade** [EOSIO/patroneos#26]
**Describe the bug**

* EOSIO HTTP chain api `push_transactions` action requires JSON Array for request body.
* but `filter.go` assumes that vaild JSON is only object not array.
* affected functions: `validateTransactionSize`, `validateMaxSignatures`, `validateContract` in `filter.go`

**To Reproduce**
Use JSON Array for request body below: 
```
'[{"code":"currency","type":"transfer","recipients":["initb","initc"],"authorization":[{"account":"initb","permission":"active"}],"data":"000000000041934b000000008041934be803000000000000"}]
```
or
```
'[{"code":"currency","type":"transfer","recipients":["initb","initc"],"authorization":[{"account":"initb","permission":"active"}],"data":"000000000041934b000000008041934be803000000000000"}, {"code":"currency","type":"transfer","recipients":["initb","initc"],"authorization":[{"account":"initb","permission":"active"}],"data":"000000000041934b000000008041934be803000000000000"}]
```
Then, got error like this:
```
2018/06/02 17:56:05 127.0.0.1:42106 false PARSING_ERROR
```

**Expected behavior**
* Like `nodeos` when request comes with JSON array, patroneos should map json array into individual transactions and validate them.

**Version (please complete the following information):**
 - OS: ubuntu 18.04 LTS
 - Patroneos Version : 48422fa05b47373ad68013f4d77d290e7fc31aae

**References**
* https://developers.eos.io/eosio-nodeos/reference#push_transactions
* https://github.com/EOSIO/eosjs-api/blob/master/src/api/v1/chain.json

**Comment by jeffreyssmith2nd** [comment]
Thanks for the detailed report, someone will look into this as soon as possible.

**Comment by jesseproudman** [comment]
Howdy! 

Just checking back in on this one to see where it is in the priority queue.

Thanks so much!

**Comment by chris-allnutt** [comment]
@jeffreyssmith2nd if this is a valid solution I can implement it and open a PR; apparently the ability for encoding/json to work on arrays has been broken since late 2017 https://stackoverflow.com/questions/22128282/easy-way-to-check-string-is-in-json-format-in-golang/36922225#36922225

**Comment by jeffreyssmith2nd** [comment]
That may be a solution, but parsing error is throw on line 142 so I think it probably is an issue with the unmarshaling of the json around line 140.

**Comment by chris-allnutt** [comment]
@jesseproudman and @redjade We've pushed a fix for this, it will be included in the next release.

**Comment by jesseproudman** [comment]
@chris-allnutt Thanks so much!
