### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by k26dr** [EOSIO/patroneos#27]
Is there a way to add CORS support through Access-Control-Allow-Origin with Patroneos?

**Comment by chris-allnutt** [comment]
@k26dr we forward all response headers this should be handled by the node itself via the http_plugin last I checked you'll need the following line in the config.ini
```
# Specify the Access-Control-Allow-Origin to be returned on each request. (eosio::http_plugin)
# access-control-allow-origin = 
```

This is the particular block in the plugin that consumes configuration information:
https://github.com/EOSIO/eos/blob/master/plugins/http_plugin/http_plugin.cpp#L235
