### ISSUE TITLE
Patroneos to return server error response code if nodeos is down

### ISSUE THREAD

**Issue by eosauthority** [EOSIO/patroneos#31]
**Describe the bug**
Currently patroneos returns HTTP 200 response and empty content even if nodeos is down and not responding. Appropriate solution will be to return some internal server error if cannot connect to nodeos. This will make it easier for detecting if a particular node is down.

**Comment by ericiles** [comment]
This has been resolved with PR #32. I will be creating a v1.0.2.rc.2 release as soon as the fixes are merged.

**Comment by eosauthority** [comment]
Great. Works well!
