### ISSUE TITLE
Parse error when using patroneos - works fine with nodeos

### ISSUE THREAD

**Issue by eosauthority** [EOSIO/patroneos#36]
**Describe the bug**
Patroneos enabled endpoing: 
curl http://publicapi-mainnet.eosauthority.com/v1/chain/get_table_rows -X POST -d '{"scope":"eosio", "code":"eosio", "table":"global", "json": true}'

Output: {"message":"PARSE_ERROR","code":400}%

Without Patroneos enabled (works as expected)
curl https://api.eosio.cr/v1/chain/get_table_rows -X POST -d '{"scope":"eosio", "code":"eosio", "table":"global", "json": true}'

Latest master version of patroneos as of now with latest latest release for BP's https://github.com/EOS-Mainnet/eos/tree/mainnet-1.0.2.2

**Comment by perduta** [comment]
Same error on our endpoint.
```
curl https://api.tokenika.io/v1/chain/get_table_rows -X POST -d '{"scope":"eosio", "code":"eosio", "table":"global", "json": true}'
{"message":"PARSE_ERROR","code":400}%
```

**Comment by ericiles** [comment]
Thanks for the report. It looks like the JSON body of this request differs from most of the other RPC requests, as scope is a string where the other transactions expect scope to be an array of strings. This is causing an unmarshalling error, as the struct it is using has scope as an array of strings.

I am working on a fix for this now.

**Comment by ericiles** [comment]
This should be resolved with PR #37

**Comment by eosauthority** [comment]
Yes, great works. Thanks for the quick fix

**Comment by matthewdarwin** [comment]
The BP validator now checks for this issue: http://validate.eosn.io/bpvalidate.txt
