### ISSUE TITLE
Set CORS header on filter?

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/patroneos#39]
Should CORS header be set on the filter by default to allow anyone to integrate with the web service?

in filter.go:

```
func forwardCallToNodeos
       ...
        copyHeaders(w.Header(), res.Header)
        w.Header().Set("Access-Control-Allow-Origin", "*")
        w.WriteHeader(res.StatusCode)
       ...
```

**Comment by ericiles** [comment]
Hi Matthew,

Patroneos is being developed as a fairly basic filter that sits in front of nodeos. It was not developed with the intention of using it as a reverse proxy, and as such lacks features one would expect from a reverse proxy. Patroneos either stops connections from getting to nodeos, or relays the request to nodeos, without modifying the response on the way back to the client.

In general, one should have a reverse proxy (hardware, HAProxy, nginx, etc.) in front of Patroneos, and the reverse proxy should be configured to add the CORS headers to the response.

**Comment by matthewdarwin** [comment]
I am currently using a very dumb reverse proxy provided by cloud hosting provider that has no option to add headers.

**Comment by ericiles** [comment]
You can also configure nodeos to add the headers by settings `access-control-allow-origin = *` in your config.ini

**Comment by matthewdarwin** [comment]
true.

**Comment by ericiles** [comment]
I am going to go ahead and re-open this. I will look into adding this functionality into Patroneos to aid in local development, and situations like yours. However, it will likely be configurable, and disabled by default.

**Comment by matthewdarwin** [comment]
Thanks... let's see if someone else needs it before you spend time on it.  Probably higher priority things for you to work on than this.

**Comment by ericiles** [comment]
This functionality is now present in master with the merging of PR #40.
